### ISSUE TITLE
Compiling CBot crashes the game if an explicitly declared constructor is called statically

### ISSUE THREAD

**Issue by pestoffne** [colobot/colobot#1410]
Colobot v0.1.12-alpha

**Steps to reproduce**
1. Copy that program to in-game program editor
```
public class Foo {
	void Foo() { }
}

public class Bar {
	public static Foo foo = new Foo();
}

extern void object::main() { }
```
2. Press "compile" button

**Expected behavior**

That code does nothing, but compiles successfully.

**Incorrect behavior**

Game crashes.
Backtrace:

```
#0  0x00007ffff7d74b8a in CBot::CBotFunction::DoCall(std::list<CBot::CBotFunction*, std::allocator<CBot::CBotFunction*> > const&, long&, std::string const&, CBot::CBotVar*, CBot::CBotVar**, CBot::CBotStack*, CBot::CBotToken*, CBot::CBotClass*) ()
   from /tmp/.mount_ColobopQeB8L/usr/bin/../lib/libCBot.so
#1  0x00007ffff7d56a51 in CBot::CBotClass::ExecuteMethode(long&, CBot::CBotVar*, CBot::CBotVar**, CBot::CBotTypResult, CBot::CBotStack*&, CBot::CBotToken*) () from /tmp/.mount_ColobopQeB8L/usr/bin/../lib/libCBot.so
#2  0x00007ffff7d7feb9 in CBot::CBotNew::Execute(CBot::CBotStack*&) () from /tmp/.mount_ColobopQeB8L/usr/bin/../lib/libCBot.so
#3  0x00007ffff7d58b11 in CBot::CBotClass::CompileDefItem(CBot::CBotToken*&, CBot::CBotCStack*, bool) ()
   from /tmp/.mount_ColobopQeB8L/usr/bin/../lib/libCBot.so
#4  0x00007ffff7d594e2 in CBot::CBotClass::DefineClasses(std::list<CBot::CBotClass*, std::allocator<CBot::CBotClass*> >, CBot::CBotCStack*) () from /tmp/.mount_ColobopQeB8L/usr/bin/../lib/libCBot.so
#5  0x00007ffff7d88815 in CBot::CBotProgram::Compile(std::string const&, std::vector<std::string, std::allocator<std::string> >&, void*) () from /tmp/.mount_ColobopQeB8L/usr/bin/../lib/libCBot.so
#6  0x00000000006b6345 in CScript::Compile() ()
#7  0x00000000006b9769 in CScript::GetScript(Ui::CEdit*) ()
#8  0x00000000005f2841 in Ui::CStudio::EventProcess(Event const&) ()
#9  0x00000000005d1a73 in Ui::CObjectInterface::EventProcess(Event const&) ()
#10 0x000000000056ea94 in COldObject::EventProcess(Event const&) ()
#11 0x000000000054a1cc in CRobotMain::EventObject(Event const&) ()
#12 0x000000000054cb51 in CRobotMain::ProcessEvent(Event&) ()
#13 0x0000000000492127 in CApplication::Run() ()
#14 0x000000000048c67f in main ()
```

Code compiles successfully without explicit constructor declaration `void Foo() { }`.

**Comment by hexagonrecursion** [comment]
This issue appears to be a duplicate of #981
