### ISSUE TITLE
Hitting vault with a flying robot causes exception

### ISSUE THREAD

**Issue by Anton-V-K** [colobot/colobot#1473]
When a flying robot hits a vault at high speed, an exception happens indicating some problem with damage calculations:
```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: D:\Games\colobot\colobot.exe
File: ..\..\..\src\physics\physics.cpp
Line: 2754

Expression: pObj->Implements(ObjectInterfaceType::Damageable)

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------
```
Fortunately pressing `Ignore` allows to continue the game, so the crash doesn't happen.

Easily and always reproducible in Alludo user level.

Colobot 0.2.0-alpha
Windows 10 21H1 64-bit

**Comment by MarcosMD09** [comment]
This means:
    The Vault doesn't have a implementation for having damage

**Comment by hexagonrecursion** [comment]
```c++
#0  0xf7fc8589 in __kernel_vsyscall ()
#1  0xf6c1f7e7 in __pthread_kill_implementation (threadid=threadid@entry=4115580928, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:43
#2  0xf6c1f85b in __pthread_kill_internal (signo=6, threadid=4115580928) at ./nptl/pthread_kill.c:78
#3  0xf6bce7a1 in __GI_raise (sig=6) at ../sysdeps/posix/raise.c:26
#4  0xf6bb62b5 in __GI_abort () at ./stdlib/abort.c:79
#5  0xf6bb61bc in __assert_fail_base (fmt=<optimized out>, assertion=<optimized out>, file=<optimized out>, line=<optimized out>, function=<optimized out>) at ./assert/assert.c:94
#6  0xf6bc69c9 in __assert_fail (assertion=0x571e4e60 "pObj->Implements(ObjectInterfaceType::Damageable)", file=0x571e4780 "/home/cdda/git/colobot/colobot-base/src/physics/physics.cpp", line=2750, 
    function=0x571e4de0 "bool CPhysics::ExploOther(ObjectType, CObject*, ObjectType, float)") at ./assert/assert.c:103
#7  0x56b78cc4 in CPhysics::ExploOther (this=0xf1f4ec80, iType=OBJECT_HUMAN, pObj=0xa361f900, oType=OBJECT_SAFE, force=43.6714821) at /home/cdda/git/colobot/colobot-base/src/physics/physics.cpp:2750
#8  0x56b76eaf in CPhysics::ObjectAdapt (this=0xf1f4ec80, pos=..., angle=...) at /home/cdda/git/colobot/colobot-base/src/physics/physics.cpp:2585
#9  0x56b64ec4 in CPhysics::EventFrame (this=0xf1f4ec80, event=...) at /home/cdda/git/colobot/colobot-base/src/physics/physics.cpp:1552
#10 0x56b591e4 in CPhysics::EventProcess (this=0xf1f4ec80, event=...) at /home/cdda/git/colobot/colobot-base/src/physics/physics.cpp:746
#11 0x56b1b4d7 in COldObject::EventProcess (this=0xa4ea8100, event=...) at /home/cdda/git/colobot/colobot-base/src/object/old_object.cpp:2144
#12 0x569ed687 in CRobotMain::EventFrame (this=0xd2e18100, event=...) at /home/cdda/git/colobot/colobot-base/src/level/robotmain.cpp:2418
#13 0x569dc225 in CRobotMain::ProcessEvent (this=0xd2e18100, event=...) at /home/cdda/git/colobot/colobot-base/src/level/robotmain.cpp:691
#14 0x56710e57 in CController::ProcessEvent (this=0xf2fd1110, event=...) at /home/cdda/git/colobot/colobot-base/src/app/controller.cpp:53
#15 0x566c00be in CApplication::Run (this=0xf4300510) at /home/cdda/git/colobot/colobot-base/src/app/app.cpp:1163
#16 0x566a7123 in main (argc=3, argv=0xffffce84) at /home/cdda/git/colobot/colobot-app/src/main.cpp:172
```
