### ISSUE TITLE
Reference loop leakes CBotVarClass, which breakes loading of save files

### ISSUE THREAD

**Issue by hexagonrecursion** [colobot/colobot#1826]
### Error message

```c++
colobot: /home/cdda/git/colobot/CBot/src/CBot/CBotVar/CBotVar.cpp:666: virtual void CBot::CBotVar::Mul(CBot::CBotVar*, CBot::CBotVar*): Assertion `0' failed.

Thread 1 "colobot" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
```

### log.txt

[log.txt](https://github.com/user-attachments/files/18217787/log.txt)

### Save file

* [savefooC.zip](https://github.com/user-attachments/files/18217789/savefooC.zip)
* [savebarC.zip](https://github.com/user-attachments/files/18217797/savebarC.zip)

### colobot.ini or colobot.json

[colobot.json](https://github.com/user-attachments/files/18217790/colobot.json)

### Game version (e.g. 0.2.1-alpha)

dev (8a40853234a054a73753a3afe7e80ff2e209f43f)

### Operating system (e.g. Windows 11)

Host: Fedora release 40 (Forty); Container: Ubuntu 24.04.1 LTS

### Steps to reproduce the crash

1. Load savefooC
2. Wait until the message "you can load the second save now" is printed
3. Load savebarC

### Are you able to reproduce the crsah?

yes

### Please post a stack trace if you know how

```c++
colobot: /home/cdda/git/colobot/CBot/src/CBot/CBotVar/CBotVar.cpp:666: virtual void CBot::CBotVar::Mul(CBot::CBotVar*, CBot::CBotVar*): Assertion `0' failed.

Thread 1 "colobot" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
warning: 44     ./nptl/pthread_kill.c: No such file or directory
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff6b6226e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff6b458ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff6b4581b in __assert_fail_base (fmt=0x7ffff6ced1e8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff77ae720 "0", 
    file=file@entry=0x7ffff77ae6c0 "/home/cdda/git/colobot/CBot/src/CBot/CBotVar/CBotVar.cpp", line=line@entry=666, function=function@entry=0x7ffff77af380 "virtual void CBot::CBotVar::Mul(CBot::CBotVar*, CBot::CBotVar*)")
    at ./assert/assert.c:94
#6  0x00007ffff6b58507 in __assert_fail (assertion=0x7ffff77ae720 "0", file=0x7ffff77ae6c0 "/home/cdda/git/colobot/CBot/src/CBot/CBotVar/CBotVar.cpp", line=666, 
    function=0x7ffff77af380 "virtual void CBot::CBotVar::Mul(CBot::CBotVar*, CBot::CBotVar*)") at ./assert/assert.c:103
#7  0x00007ffff77474ad in CBot::CBotVar::Mul (this=0x50d000006360, left=0x50d000006290, right=0x50e0005a0980) at /home/cdda/git/colobot/CBot/src/CBot/CBotVar/CBotVar.cpp:666
#8  0x00007ffff7715d0f in CBot::CBotTwoOpExpr::Execute (this=0x50f000089200, pStack=@0x7ffff35bc260: 0x5330002309a0) at /home/cdda/git/colobot/CBot/src/CBot/CBotInstr/CBotTwoOpExpr.cpp:455
#9  0x00007ffff7702837 in CBot::CBotListInstr::Execute (this=0x50e00028fe20, pj=@0x7ffff35bbc60: 0x533000230938) at /home/cdda/git/colobot/CBot/src/CBot/CBotInstr/CBotListInstr.cpp:91
#10 0x00007ffff7718d2f in CBot::CBotWhile::Execute (this=0x5110076b49c0, pj=@0x7ffff35bbc20: 0x5330002308d0) at /home/cdda/git/colobot/CBot/src/CBot/CBotInstr/CBotWhile.cpp:112
#11 0x00007ffff7702837 in CBot::CBotListInstr::Execute (this=0x50e00028f800, pj=@0x7ffff3882640: 0x533000230868) at /home/cdda/git/colobot/CBot/src/CBot/CBotInstr/CBotListInstr.cpp:91
#12 0x00007ffff76dfb05 in CBot::CBotFunction::Execute (this=0x5190000cc180, ppVars=0x0, pj=@0x508000011cd8: 0x533000230800, pInstance=0x50c000021580) at /home/cdda/git/colobot/CBot/src/CBot/CBotInstr/CBotFunction.cpp:448
#13 0x00007ffff771bf7f in CBot::CBotProgram::Run (this=0x508000011ca0, pUser=0x512000030040, timer=100) at /home/cdda/git/colobot/CBot/src/CBot/CBotProgram.cpp:198
#14 0x00005555560ed5d9 in CScript::Continue (this=0x512000030040) at /home/cdda/git/colobot/colobot-base/src/script/script.cpp:369
#15 0x0000555555f926d4 in CProgrammableObjectImpl::EventProcess (this=0x527000268208, event=...) at /home/cdda/git/colobot/colobot-base/src/object/implementation/programmable_impl.cpp:81
#16 0x0000555555bff986 in COldObject::EventProcess (this=0x527000268100, event=...) at /home/cdda/git/colobot/colobot-base/src/object/old_object.cpp:2314
#17 0x0000555555aca933 in CRobotMain::EventFrame (this=0x523000034900, event=...) at /home/cdda/git/colobot/colobot-base/src/level/robotmain.cpp:2419
#18 0x0000555555aba550 in CRobotMain::ProcessEvent (this=0x523000034900, event=...) at /home/cdda/git/colobot/colobot-base/src/level/robotmain.cpp:691
#19 0x00005555557cd3de in CController::ProcessEvent (this=0x5020000d9db0, event=...) at /home/cdda/git/colobot/colobot-base/src/app/controller.cpp:53
#20 0x000055555577da94 in CApplication::Run (this=0x7ffff3b01530) at /home/cdda/git/colobot/colobot-base/src/app/app.cpp:1163
#21 0x0000555555764d0d in main (argc=3, argv=0x7fffffffe908) at /home/cdda/git/colobot/colobot-app/src/main.cpp:172
```

### Installed mods (if any)

None

### Additional information

* This is similar to #1825, but instead of CBotProgram destructor leaking a CBotVarClass instance the instance is leaked because we use reference counting and can not properly detect and deallocate reference loops (note: even though in this case the loop has the length of 1 in general the loop many be arbitrarily long requiring a tracing garbage collector e.g. mark-and-sweep)

The program running in save foo:
```c++
public class Foo
{
	string s = "s";
	Foo f = null;
}

extern void New()
{
	Foo a = new Foo();
	wait(3);
	a.f = a;
	a = null;
	message("you can load the second save now");
}
```

The program running in save bar:
```c++
public class Bar {
	int i = 1;
};

extern void New()
{
	int j;
	int k;
	Bar b();
	while(true)
	{
		b.i * 2;
	}
}
```

**Comment by hexagonrecursion** [comment]
Here is a different way to reproduce this bug:
1. Start the below program
2. Quicksave
3. Wait for the countdown to reach 0
4. Wait for the game will print "load"
5. Quickload
6. Wait for the countdown to reach 0
7. The game will print "expected: 1, got: 2".

```c++
public class Foo
{
	int i = 1;
	Foo f = null;
}

extern void New()
{
	Foo f = new Foo;
	message("save");
	for(int i = 5; i >= 0; --i)
	{
		wait(2);
		message(i);
	}
	message("expected: 1, got: " + f.i);
	f.i = 2;
	f.f = f;
	f = null;
	message("load");
}
```

![image](https://github.com/user-attachments/assets/146bc9f7-2475-416a-80cf-ec1f4f2b36b4)
