### ISSUE TITLE
Crash "When opening SatCom (after pressing F1 at the beginning of mission 2.4)"

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#439]
```
#0  0x00000026 in ?? ()
#1  0xb7a30fcf in PHYSFS_tell () from /usr/lib/i386-linux-gnu/libphysfs.so.1
#2  0xb7a31298 in PHYSFS_seek () from /usr/lib/i386-linux-gnu/libphysfs.so.1
#3  0x080d427f in CResourceManager::SDLSeek (context=0x92dad58, offset=51644,
    whence=0)
    at /home/user/colobot/src/common/resources/resourcemanager.cpp:351
#4  0xb7ecc5e5 in ?? () from /usr/lib/i386-linux-gnu/libSDL_ttf-2.0.so.0
#5  0xb7260b6c in FT_Stream_Seek ()
   from /usr/lib/i386-linux-gnu/libfreetype.so.6
#6  0xb729f07f in ?? () from /usr/lib/i386-linux-gnu/libfreetype.so.6
#7  0xb7276ad6 in ?? () from /usr/lib/i386-linux-gnu/libfreetype.so.6
#8  0xb72783c5 in ?? () from /usr/lib/i386-linux-gnu/libfreetype.so.6
#9  0xb7264e27 in FT_Load_Glyph ()
   from /usr/lib/i386-linux-gnu/libfreetype.so.6
#10 0xb7ecc932 in ?? () from /usr/lib/i386-linux-gnu/libSDL_ttf-2.0.so.0
#11 0xb7ecdb39 in TTF_SizeUNICODE ()
   from /usr/lib/i386-linux-gnu/libSDL_ttf-2.0.so.0
#12 0xb7ecde91 in TTF_SizeUTF8 ()
   from /usr/lib/i386-linux-gnu/libSDL_ttf-2.0.so.0
#13 0x08113e4b in Gfx::CText::GetCharWidth (this=this@entry=0x8a99380,
    ch=ch@entry=..., font=font@entry=Gfx::FONT_COLOBOT,
    size=size@entry=19.2000008, offset=offset@entry=0)
    at /home/user/colobot/src/graphics/engine/text.cpp:381
#14 0x081141a3 in Gfx::CText::Justify (this=0x8a99380,
    text="Procedura\n1) Na początek zbuduj hutę, w której przetopisz posiadane już kawałki rudy tytanu w użyteczne kostki tytanu.\n2) Następnie zbuduj stację energetyczną oraz radar, który wskaże na ma"...,
    format=format@entry=16, end=end@entry=0, size=size@entry=19.2000008,
    width=width@entry=0.9296875)
    at /home/user/colobot/src/graphics/engine/text.cpp:421
#15 0x081b5586 in Ui::CEdit::Justif (this=this@entry=0x98bbbb0)
    at /home/user/colobot/src/ui/edit.cpp:3009
#16 0x081ba28a in Ui::CEdit::ReadText (this=this@entry=0x98bbbb0,
    filename="levels/missions/chapter002/level004/help/help.P.txt",
    addSize=addSize@entry=0) at /home/user/colobot/src/ui/edit.cpp:1840
#17 0x081b1534 in Ui::CDisplayInfo::StartDisplayInfo (this=0x9832218,
    filename="levels/missions/chapter002/level004/help/help.P.txt",
    index=index@entry=0, bSoluce=bSoluce@entry=false)
    at /home/user/colobot/src/ui/displayinfo.cpp:383
#18 0x08161765 in CRobotMain::StartDisplayInfo (this=0x8af6b40,
    filename=0x8af6c8c "levels/missions/chapter002/level004/help/help.P.txt",
    index=0) at /home/user/colobot/src/object/robotmain.cpp:1456
#19 0x0817c9e9 in CRobotMain::ProcessEvent (this=0x8af6b40, event=...)
    at /home/user/colobot/src/object/robotmain.cpp:852
#20 0x080ba743 in CController::ProcessEvent (this=0x8af6b40, event=...)
    at /home/user/colobot/src/app/controller.cpp:87
#21 0x080b649a in CApplication::Run (this=this@entry=0x8334ae0)
    at /home/user/colobot/src/app/app.cpp:999
#22 0x080aeda9 in main (argc=3, argv=0xbffff4b4)
    at /home/user/colobot/src/app/main.cpp:122
```
Maybe related to #397
Reported by @tomangelo2

**Comment by krzys-h** [comment]
Is this reproducible in any way?

**Comment by piotrdz** [comment]
I think that code should be more stable after recent refactoring and removing manual memory management. To be sure, some code in CText should be refactored further to remove raw pointer management. But once that is done, I would not expect any crashes here.

**Comment by Erihel** [comment]
Can't reproduce crash with recent commit.

**Comment by krzys-h** [comment]
Not reproducible, so closing this issue
