### ISSUE TITLE
Ground texture disappear when rebooting Exercise level

### ISSUE THREAD

**Issue by RaptorParkowsky** [colobot/colobot#498]
After I click on "Return to start" button in bot's UI, the ground texture disappear for a moment:
![schowek01](https://cloud.githubusercontent.com/assets/4019345/8595284/01dacb98-2649-11e5-8ae4-7e9f50896caa.png)

It happen only when I have shadows turned on. Probably something wrong with maximum texture units. For OpenGL 1.5 my GPU have maximum 4 texture units. For the OpenGL 2.1 I have 16 texture units, but the game crashes, when I click on "Return to start" button.

**Comment by Erihel** [comment]
Can't confirm this. Works fine for me under Linux and Radeon 6870. Checked with OpenGL 1.5 and 2.1

**Comment by krzys-h** [comment]
***OpenGL 1.5***
```[INFO]: Maximum texture units: 8```
Can't reproduce.

***OpenGL 2.1***
```[INFO]: Maximum texture image units: 32```
Well, terrain still doesn't work for me at all on this engine, so I can't really check.
But it crashes on clicking that button, I'm not sure if this is related to this bug or not.
```
colobot: /home/krzys_h/Pulpit/colobot/src/math/matrix.h:361: Math::Matrix Math::Matrix::Inverse() const: Warunek zapewnienia `! IsZero(d)' nie został spełniony.

Program received signal SIGABRT, Aborted.
0x00007ffff4e3a267 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: Nie ma takiego pliku ani katalogu.
(gdb) bt
#0  0x00007ffff4e3a267 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff4e3beca in __GI_abort () at abort.c:89
#2  0x00007ffff4e3303d in __assert_fail_base (
    fmt=0x7ffff7e8e11d "%s%s%s:%u: %s%sWarunek zapewnienia `%s' nie został spełniony.\n%n", assertion=assertion@entry=0x8dfc99 "! IsZero(d)", 
    file=file@entry=0x8dfc48 "/home/krzys_h/Pulpit/colobot/src/math/matrix.h", 
    line=line@entry=361, 
    function=function@entry=0x8e0320 <Math::Matrix::Inverse() const::__PRETTY_FUNCTION__> "Math::Matrix Math::Matrix::Inverse() const") at assert.c:92
#3  0x00007ffff4e330f2 in __GI___assert_fail (
    assertion=0x8dfc99 "! IsZero(d)", 
    file=0x8dfc48 "/home/krzys_h/Pulpit/colobot/src/math/matrix.h", line=361, 
    function=0x8e0320 <Math::Matrix::Inverse() const::__PRETTY_FUNCTION__> "Math::Matrix Math::Matrix::Inverse() const") at assert.c:101
#4  0x00000000007d3021 in Math::Matrix::Inverse (this=0x7fffffffde30)
    at /home/krzys_h/Pulpit/colobot/src/math/matrix.h:361
#5  0x00000000007cd354 in Gfx::CGL21Device::SetTransform (this=0x317ee70, 
    type=Gfx::TRANSFORM_WORLD, matrix=...)
    at /home/krzys_h/Pulpit/colobot/src/graphics/opengl/gl21device.cpp:425
#6  0x000000000063619e in Gfx::CEngine::RenderShadowMap (this=0x43d0b70)
    at /home/krzys_h/Pulpit/colobot/src/graphics/engine/engine.cpp:3504
#7  0x00000000006340ae in Gfx::CEngine::Render (this=0x43d0b70)
    at /home/krzys_h/Pulpit/colobot/src/graphics/engine/engine.cpp:3095
#8  0x00000000005eb422 in CApplication::Render (this=0xbc1420)
    at /home/krzys_h/Pulpit/colobot/src/app/app.cpp:1236
#9  0x00000000005ea76d in CApplication::Run (this=0xbc1420)
    at /home/krzys_h/Pulpit/colobot/src/app/app.cpp:994
#10 0x00000000005e5ad3 in main (argc=3, argv=0x7fffffffe3b8)
    at /home/krzys_h/Pulpit/colobot/src/app/main.cpp:146
```

**Comment by RaptorParkowsky** [comment]
I the newest debug build I can't reproduce that now in standard OpenGL 1.4 and max texture unit = 4. Moreover in OpenGL 2.1 game doesn't crash now. If someone else can verify this, I think this issue can be closed.
