### ISSUE TITLE
Crash after opening SatCom - Satellite view

### ISSUE THREAD

**Issue by tomangelo2** [colobot/colobot#519]
Only happen on dev-release build, on dev-debug there is everything allright.
```
Program received signal SIGSEGV, Segmentation fault.
0x007ec86d in PHYSFS_tell (handle=0xaa88568)
    at /opt/mxe/tmp-physfs/physfs-2.0.3/physfs.c:2038
2038    /opt/mxe/tmp-physfs/physfs-2.0.3/physfs.c: No such file or directory.
(gdb) backtrace
#0  0x007ec86d in PHYSFS_tell (handle=0xaa88568)
    at /opt/mxe/tmp-physfs/physfs-2.0.3/physfs.c:2038
#1  PHYSFS_seek (handle=0xaa88568, pos=22900)
    at /opt/mxe/tmp-physfs/physfs-2.0.3/physfs.c:2054
#2  0x0041121f in CSDLFileWrapper::SDLSeek(SDL_RWops*, int, int) ()
#3  0x00636c5a in RWread (stream=0x19e67b38, offset=22900, buffer=0x0,
    count=0) at SDL_ttf.c:365
#4  0x00729d1d in FT_Stream_Seek (stream=0x19e67b38, pos=22900)
    at /opt/mxe/tmp-freetype/freetype-2.5.0.1/src/base/ftstream.c:65
#5  0x0073be0b in tt_loader_init (loader=loader@entry=0x22f750,
    size=size@entry=0x19e97718, glyph=glyph@entry=0x19e975e8,
    load_flags=load_flags@entry=0, glyf_table_only=<optimized out>,
    glyf_table_only@entry=0 '\000')
    at /opt/mxe/tmp-freetype/freetype-2.5.0.1/src/truetype/ttgload.c:2133
#6  0x0073d652 in TT_Load_Glyph (load_flags=0, glyph_index=36,
    glyph=0x19e975e8, size=0x19e97718)
    at /opt/mxe/tmp-freetype/freetype-2.5.0.1/src/truetype/ttgload.c:2249
#7  tt_glyph_load (ttslot=0x19e975e8, ttsize=0x19e97718, glyph_index=36,
    load_flags=0)
    at /opt/mxe/tmp-freetype/freetype-2.5.0.1/src/truetype/ttdriver.c:403
#8  0x007293af in FT_Load_Glyph (face=face@entry=0x19e96d20,
    glyph_index=glyph_index@entry=36, load_flags=load_flags@entry=0)
    at /opt/mxe/tmp-freetype/freetype-2.5.0.1/src/base/ftobjs.c:721
#9  0x0072988b in FT_Load_Glyph (face=face@entry=0x19e96d20, glyph_index=36,
    load_flags=0)
    at /opt/mxe/tmp-freetype/freetype-2.5.0.1/src/base/ftobjs.c:603
#10 0x00636f77 in Load_Glyph (want=16, cached=0x19eec594, ch=65,
    font=0x19eeb008) at SDL_ttf.c:593
#11 Find_Glyph (font=font@entry=0x19eeb008, ch=<optimized out>,
    want=want@entry=16) at SDL_ttf.c:901
#12 0x0063802b in TTF_SizeUNICODE (font=font@entry=0x19eeb008,
    text=<optimized out>, text@entry=0xab6ebd0, w=w@entry=0x22f9c8,
    h=h@entry=0x22f9cc) at SDL_ttf.c:1156
#13 0x006382fa in TTF_SizeUTF8 (font=0x19eeb008, text=0x19dd3a64 "A",
    w=0x22f9c8, h=0x22f9cc) at SDL_ttf.c:1095
#14 0x00486192 in Gfx::CText::GetCharWidth(Gfx::UTF8Char, Gfx::FontType, float,
float) ()
#15 0x004864bc in Gfx::CText::Justify(std::string const&, __gnu_cxx::__normal_it
erator<short*, std::vector<short, std::allocator<short> > >, __gnu_cxx::__normal
_iterator<short*, std::vector<short, std::allocator<short> > >, float, float) ()

#16 0x0050ae2a in Ui::CEdit::Justif() ()
#17 0x0050bd55 in Ui::CEdit::Scroll(int, bool) ()
#18 0x0050bf09 in Ui::CEdit::SetFirstLine(int) ()
#19 0x004d7cdc in Ui::CDisplayInfo::ChangeIndexButton(int) ()
#20 0x004d834f in Ui::CDisplayInfo::EventProcess(Event const&) ()
#21 0x004594fe in CRobotMain::ProcessEvent(Event&) ()
#22 0x0040e73d in CApplication::Run() ()
#23 0x00401517 in SDL_main ()
#24 0x005f919e in console_main (argc=argc@entry=1, argv=argv@entry=0x1bc28a8)
    at ./src/main/win32/SDL_win32_main.c:315
#25 0x005f9258 in WinMain@16 (hInst=0x400000, hPrev=warning: (Internal error: pc
 0x0 in read in psymtab, but not in symtab.)

0x0,
    szCmdLine=0x241f07 "", sw=10) at ./src/main/win32/SDL_win32_main.c:398
#26 0x008ae78b in main ()
(gdb)
```

**Comment by krzys-h** [comment]
This might be related to commit 8ca77f27a16e8af123284a3a9d9f059336aaecbf

**Comment by piotrdz** [comment]
It is definitely related to this part of code, but I think this bug has been here from the beginning and my refactoring and fixing manual memory management didn't change anything.

I'll take a look into that, but that may take a while as I'll need to reproduce this bug on my machine.

**Comment by krzys-h** [comment]
I can't reproduce this on newest release build from Jenkins.

**Comment by tomangelo2** [comment]
It still occur, but it seems like it happen randomly.

**Comment by tomangelo2** [comment]
Now it doesn't happen anymore, so I close this issue. If it occur again, I'll reopen this.
