### ISSUE TITLE
Save / load is not robust for deleting CreateObject-s from data.sav

### ISSUE THREAD

**Issue by attila123** [colobot/colobot#614]
Latest dev.
Because of the Tiny Ant bug #610 I wanted to delete the problematic ants from the data.sav file manually, so I tried it. But it causes crash at the end of loading the saved game.
To reproduce:
- take savegame I posted for #610 
- open data.sav, and delete the first CreateObject line with AlienAnt (line 42), and save data.sav
- try to load the saved game
- at the end of loading it crashes:
```
[DEBUG]: Loading saved scene programs from 'savegame/Player/save1508290251Terran
ova4/prog856___.txt'

Unhandled exception occured!
==============================
SIGSEGV, segmentation fault
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot
/colobot/issues
including information on what you were doing before this happened and all the in
formation below.
==============================
You are running version git-HEAD~r934d97a from CI build #93

The game was in phase PHASE_SIMUL (ID=7)
Last started level was: category=missions chap=9 rank=4
==============================

Sorry for inconvenience!
```
I know it can be considered as a cheat, but It would be nice if this worked.
Tried this on Windows.

**Comment by attila123** [comment]
Thx.
alpha-0.1.5 milestone?

**Comment by krzys-h** [comment]
Sorry, the GitHub Android app shows also closed milestones for some reason, I must've misclicked

**Comment by krzys-h** [comment]
This is problem in the CBot library, so I'm moving this issue to 0.2.0 milestone. As a workaround, you can remove the cbot.run file, but that has a side effect of restarting all the programs (it usually doesn't load properly anyway...)
```
Program received signal SIGSEGV, Segmentation fault.
0x000000006d153139 in CBotFunction::RestoreState (this=0x0, ppVars=0x0,
    pj=@0x20cd9d68: 0x256409d0, pInstance=0x20bf3dc0)
    at C:/Users/krzys_h/Desktop/colobot/src/CBot/CBotFunction.cpp:435
435         pile->SetBotCall(m_pProg);                          // bases for routines
(gdb) bt
#0  0x000000006d153139 in CBotFunction::RestoreState (this=0x0, ppVars=0x0,
    pj=@0x20cd9d68: 0x256409d0, pInstance=0x20bf3dc0)
    at C:/Users/krzys_h/Desktop/colobot/src/CBot/CBotFunction.cpp:435
#1  0x000000006d1596f3 in CBotProgram::RestoreState (this=0x20cd9d50,
    pf=0x7ffa31263d60 <msvcrt!_iob+144>)
    at C:/Users/krzys_h/Desktop/colobot/src/CBot/CBotProgram.cpp:548
#2  0x00000000005e7c1f in CScript::ReadStack (this=0x20cd7020,
    file=0x7ffa31263d60 <msvcrt!_iob+144>)
    at C:/Users/krzys_h/Desktop/colobot/src/script/script.cpp:1038
#3  0x000000000058d977 in CProgrammableObjectImpl::ReadStack (
    this=0x20c0fd20, file=0x7ffa31263d60 <msvcrt!_iob+144>)
    at C:/Users/krzys_h/Desktop/colobot/src/object/implementation/programmable_impl.cpp:155
#4  0x000000000048613f in CRobotMain::ReadFileStack (this=0x5c6e200, obj=
    0x20c0fc20, file=0x7ffa31263d60 <msvcrt!_iob+144>, objRank=52)
    at C:/Users/krzys_h/Desktop/colobot/src/level/robotmain.cpp:4370
#5  0x000000000048afa8 in CRobotMain::IOReadScene (this=0x5c6e200,
    filename=..., filecbot=...)
    at C:/Users/krzys_h/Desktop/colobot/src/level/robotmain.cpp:4833
#6  0x000000000047a1cf in CRobotMain::CreateScene (this=0x5c6e200,
    soluce=false, fixScene=false, resetObject=false)
    at C:/Users/krzys_h/Desktop/colobot/src/level/robotmain.cpp:3302
#7  0x0000000000469915 in CRobotMain::ChangePhase (this=0x5c6e200,
    phase=PHASE_SIMUL)
    at C:/Users/krzys_h/Desktop/colobot/src/level/robotmain.cpp:539
#8  0x000000000057f580 in CPlayerProfile::LoadScene (this=0x5c07020, dir=...)
    at C:/Users/krzys_h/Desktop/colobot/src/level/player_profile.cpp:522
#9  0x00000000005ef966 in Ui::CScreenIO::IOReadScene (this=0x5c71500)
    at C:/Users/krzys_h/Desktop/colobot/src/ui/screen/screen_io.cpp:257
#10 0x0000000000533388 in Ui::CScreenIORead::EventProcess (this=0x5c71500,
    event=...)
    at C:/Users/krzys_h/Desktop/colobot/src/ui/screen/screen_io_read.cpp:169
#11 0x00000000004fda7e in Ui::CMainUserInterface::EventProcess (
    this=0x5c71080, event=...)
    at C:/Users/krzys_h/Desktop/colobot/src/ui/mainui.cpp:235
#12 0x000000000046a4c2 in CRobotMain::ProcessEvent (this=0x5c6e200, event=...)
    at C:/Users/krzys_h/Desktop/colobot/src/level/robotmain.cpp:643
#13 0x0000000000408d83 in CController::ProcessEvent (this=0x5b2c000,
    event=...) at C:/Users/krzys_h/Desktop/colobot/src/app/controller.cpp:66
#14 0x0000000000406215 in CApplication::Run (this=0x23f9f0)
    at C:/Users/krzys_h/Desktop/colobot/src/app/app.cpp:984
#15 0x0000000000401abb in SDL_main (argc=1, argv=0x3fd530)
    at C:/Users/krzys_h/Desktop/colobot/src/app/main.cpp:162
#16 0x00000000006136b0 in console_main ()
#17 0x00000000003fd530 in ?? ()
#18 0x00000000003fd330 in ?? ()
#19 0x00000000003fd2c0 in ?? ()
#20 0x0000000000000001 in ?? ()
#21 0x00000000003fd330 in ?? ()
#22 0x00000000003fd2c0 in ?? ()
#23 0x0000000000000001 in ?? ()
#24 0x00000000003f9110 in ?? ()
#25 0x0000000000613772 in WinMain ()
#26 0x0000000000000038 in ?? ()
#27 0x00000000003fd2c0 in ?? ()
#28 0x0000000000864ec0 in __onexitbegin ()
#29 0x0000000000000004 in ?? ()
#30 0x0000000000000001 in ?? ()
#31 0x0000000000000035 in ?? ()
#32 0x00000000003f9150 in ?? ()
#33 0x00000000004013e8 in __tmainCRTStartup ()
    at C:/git/mingw/mingw-w64-crt-git/src/crt/mingw-w64-crt/crt/crtexe.c:332
#34 0x000000000040151b in mainCRTStartup ()
    at C:/git/mingw/mingw-w64-crt-git/src/crt/mingw-w64-crt/crt/crtexe.c:212
(gdb)
```

**Comment by hexagonrecursion** [comment]
I think this bug should be closed as "not planned". We can say that editing of save files is not officially supported - if you change anything, you are on your own
