### ISSUE TITLE
Crash related to TTF and PHYSFS (in SatCom?)

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#708]
I think I saw this already in some other issue, can't find it now. I think @piotrdz was working on fixing this at some point. Happened after clicking a link in SatCom.
```
(gdb) bt
#0  0x00007fceb45e389b in __GI___waitpid (pid=14702, stat_loc=stat_loc@entry=0x7ffc72ec0b80, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
#1  0x00007fceb455cffb in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00000000007bd294 in CSystemUtilsLinux::SystemDialog (this=0x119a800, type=SDT_YES_NO, title="Try to save?", 
    message="You can try saving the game at the moment of a crash. Keep in mind, the game engine is in\nan unstable state so the saved game may be corrupted or even cause another crash.\n\nDo you want to try saving n"...) at /home/krzys_h/Pulpit/colobot/src/app/system_linux.cpp:68
#3  0x00000000007ba52f in CSignalHandlers::ReportError (errorMessage="SIGSEGV, segmentation fault") at /home/krzys_h/Pulpit/colobot/src/app/signal_handlers.cpp:175
#4  0x00000000007b9990 in CSignalHandlers::SignalHandler (sig=11) at /home/krzys_h/Pulpit/colobot/src/app/signal_handlers.cpp:57
#5  <signal handler called>
#6  0x00007fceb518c8cb in PHYSFS_tell () from /usr/lib/x86_64-linux-gnu/libphysfs.so.1
#7  0x00007fceb518cc08 in PHYSFS_seek () from /usr/lib/x86_64-linux-gnu/libphysfs.so.1
#8  0x00000000007deaad in CSDLFileWrapper::SDLSeek (context=0x5db2d70, offset=22900, whence=0) at /home/krzys_h/Pulpit/colobot/src/common/resources/sdl_file_wrapper.cpp:132
#9  0x00007fceb66efd59 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0
#10 0x00007fceb1635a2b in FT_Stream_Seek () from /usr/lib/x86_64-linux-gnu/libfreetype.so.6
#11 0x00007fceb164c908 in ?? () from /usr/lib/x86_64-linux-gnu/libfreetype.so.6
#12 0x00007fceb164d0bc in ?? () from /usr/lib/x86_64-linux-gnu/libfreetype.so.6
#13 0x00007fceb16378bb in FT_Load_Glyph () from /usr/lib/x86_64-linux-gnu/libfreetype.so.6
#14 0x00007fceb66f0201 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0
#15 0x00007fceb66f2477 in TTF_RenderUTF8_Blended () from /usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0
#16 0x000000000085c454 in Gfx::CText::CreateCharTexture (this=0x347ead0, ch=..., font=0x5dafd30) at /home/krzys_h/Pulpit/colobot/src/graphics/engine/text.cpp:1009
#17 0x000000000085c748 in Gfx::CText::GetCharTexture (this=0x347ead0, ch=..., font=Gfx::FONT_COURIER, size=24,3199997) at /home/krzys_h/Pulpit/colobot/src/graphics/engine/text.cpp:1068
#18 0x000000000085b848 in Gfx::CText::DrawCharAndAdjustPos (this=0x347ead0, ch=..., font=Gfx::FONT_COURIER, size=24,3199997, pos=..., color=...)
    at /home/krzys_h/Pulpit/colobot/src/graphics/engine/text.cpp:927
#19 0x000000000085a2fd in Gfx::CText::DrawString (this=0x347ead0, text="Instrukcja strval", format=16, end=65, size=24,3199997, pos=..., width=0,721875012, eol=0, color=...)
    at /home/krzys_h/Pulpit/colobot/src/graphics/engine/text.cpp:697
#20 0x000000000085855e in Gfx::CText::DrawText (this=0x347ead0, text="Instrukcja strval", format=16, end=65, size=24,3199997, pos=..., width=0,721875012, align=Gfx::TEXT_ALIGN_LEFT, eol=0, color=...)
    at /home/krzys_h/Pulpit/colobot/src/graphics/engine/text.cpp:204
#21 0x000000000097cc33 in Ui::CEdit::Draw (this=0x5cfff60) at /home/krzys_h/Pulpit/colobot/src/ui/controls/edit.cpp:1071
#22 0x00000000009a7d6f in Ui::CWindow::Draw (this=0x5cb86a0) at /home/krzys_h/Pulpit/colobot/src/ui/controls/window.cpp:887
#23 0x000000000098b993 in Ui::CInterface::Draw (this=0x4a28220) at /home/krzys_h/Pulpit/colobot/src/ui/controls/interface.cpp:347
#24 0x00000000007f6604 in Gfx::CEngine::DrawInterface (this=0x347de80) at /home/krzys_h/Pulpit/colobot/src/graphics/engine/engine.cpp:3802
#25 0x00000000007f2b26 in Gfx::CEngine::Render (this=0x347de80) at /home/krzys_h/Pulpit/colobot/src/graphics/engine/engine.cpp:3128
#26 0x00000000007a3a81 in CApplication::Render (this=0x7ffc72ec2660) at /home/krzys_h/Pulpit/colobot/src/app/app.cpp:1254
#27 0x00000000007a297e in CApplication::Run (this=0x7ffc72ec2660) at /home/krzys_h/Pulpit/colobot/src/app/app.cpp:959
#28 0x000000000079e3a3 in main (argc=1, argv=0x7ffc72ec2a88) at /home/krzys_h/Pulpit/colobot/src/app/main.cpp:165
(gdb) frame 8
#8  0x00000000007deaad in CSDLFileWrapper::SDLSeek (context=0x5db2d70, offset=22900, whence=0) at /home/krzys_h/Pulpit/colobot/src/common/resources/sdl_file_wrapper.cpp:132
132	                auto result = PHYSFS_seek(file, offset);
(gdb) info locals
result = 0
file = 0x5d9a9c0
(gdb) p *context
$2 = {size = 0x7deb60 <CSDLFileWrapper::SDLSize(SDL_RWops*)>, seek = 0x7dea5a <CSDLFileWrapper::SDLSeek(SDL_RWops*, long, int)>, 
  read = 0x7deb72 <CSDLFileWrapper::SDLRead(SDL_RWops*, void*, unsigned long, unsigned long)>, write = 0x7debfc <CSDLFileWrapper::SDLWrite(SDL_RWops*, void const*, unsigned long, unsigned long)>, 
  close = 0x7de9e2 <CSDLFileWrapper::SDLCloseWithoutFreeRW(SDL_RWops*)>, type = 3222319183, hidden = {stdio = {autoclose = (unknown: 98150848), 
      fp = 0x8d68e1 <boost::iterators::iterator_adaptor<boost::iterators::transform_iterator<boost::algorithm::detail::copy_iterator_rangeF<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, boost::algorithm::split_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, boost::iterators::use_default, boost::iterators::use_default>, boost::algorithm::split_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::iterators::use_default, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::iterators::use_default>::iterator_adaptor(boost::iterators::iterator_adaptor<boost::iterators::transform_iterator<boost::algorithm::detail::copy_iterator_rangeF<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, boost::algorithm::split_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, boost::iterators::use_default, boost::iterators::use_default>, boost::algorithm::split_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::iterators::use_default, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::iterators::use_default> const&)+35>}, mem = {base = 0x5d9a9c0 "", 
      here = 0x8d68e1 <boost::iterators::iterator_adaptor<boost::iterators::transform_iterator<boost::algorithm::detail::copy_iterator_rangeF<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, boost::algorithm::split_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, boost::iterators::use_default, boost::iterators::use_default>, boost::algorithm::split_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::iterators::use_default, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::iterators::use_default>::iterator_adaptor(boost::iterators::iterator_adaptor<boost::iterators::transform_iterator<boost::algorithm::detail::copy_iterator_rangeF<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, boost::algorithm::split_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, boost::iterators::use_default, boost::iterators::use_default>, boost::algorithm::split_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::iterators::use_default, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::iterators::use_default> const&)+35> "\220\311\303UH\211\345H\203\354\020H\211}\370H\211u\360H\213U\360H\213E\370H\211\326H\211\307\350\267\377\377\377\220\311\303UH\211\345ATSH\201\354 \002", 
      stop = 0x0}, unknown = {data1 = 0x5d9a9c0, 
      data2 = 0x8d68e1 <boost::iterators::iterator_adaptor<boost::iterators::transform_iterator<boost::algorithm::detail::copy_iterator_rangeF<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, boost::algorithm::split_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, boost::iterators::use_default, boost::iterators::use_default>, boost::algorithm::split_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::iterators::use_default, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::iterators::use_default>::iterator_adaptor(boost::iterators::iterator_adaptor<boost::iterators::transform_iterator<boost::algorithm::detail::copy_iterator_rangeF<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, boost::algorithm::split_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, boost::iterators::use_default, boost::iterators::use_default>, boost::algorithm::split_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::iterators::use_default, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::iterators::use_default> const&)+35>}}}
(gdb) frame 16
#16 0x000000000085c454 in Gfx::CText::CreateCharTexture (this=0x347ead0, ch=..., font=0x5dafd30) at /home/krzys_h/Pulpit/colobot/src/graphics/engine/text.cpp:1009
1009	    textSurface = TTF_RenderUTF8_Blended(font->font, str, white);
(gdb) info locals
texture = {id = 0, texSize = {x = 0, y = 0}, charSize = {x = 0, y = 0}}
textSurface = 0x0
white = {r = 255 '\377', g = 255 '\377', b = 255 '\377', a = 0 '\000'}
str = "s\000\000"
w = 1715538688
h = 434505100
textureSurface = 0x85ed9e <std::_Rb_tree<Gfx::UTF8Char, std::pair<Gfx::UTF8Char const, Gfx::CharTexture>, std::_Select1st<std::pair<Gfx::UTF8Char const, Gfx::CharTexture> >, std::less<Gfx::UTF8Char>, std::allocator<std::pair<Gfx::UTF8Char const, Gfx::CharTexture> > >::end()+50>
data = {surface = 0x7ffc72ec1d40}
createParams = {mipmap = 72, format = Gfx::TEX_IMG_AUTO, filter = (unknown: 98237760), padToNearestPowerOfTwo = false}
tex = {id = 98237768, size = {x = 0, y = 1715538688}, originalSize = {x = 434505100, y = 1928076640}, alpha = 252}
```

**Comment by krzys-h** [comment]
Just in case, I did save a core dump file, so if you need any additional info please tell me.

**Comment by krzys-h** [comment]
@Erihel just mentioned the old issue I couldn't find - #519 ;)
