### ISSUE TITLE
SIGSEGV, segmentation fault on ARM (Raspberry Pi 3)

### ISSUE THREAD

**Issue by azureblue** [colobot/colobot#788]
Console out:
[INFO]: Colobot: Gold Edition 0.1.7b-alpha starting
[INFO]: Using data dir: './data'
[INFO]: Creating CApplication
[WARN]: Language path '/usr/local/share/locale' is invalid, assuming translation files not installed
[WARN]: Unable to load mods from directory './data/mods': boost::filesystem::directory_iterator::construct: No such file or directory: "./data/mods"
[INFO]: Data path: ./data
[INFO]: Save path: /home/pi/.local/share/colobot
[INFO]: Opening audio device...
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
[INFO]: Done.
[INFO]: CApplication created successfully
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLVersion)
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLProfile)
[INFO]: Error on parsing config file: No such node (Experimental.MSAA)
[INFO]: Error on parsing config file: No such node (Experimental.VSync)
[INFO]: No joysticks detected
[INFO]: Error on parsing config file: No such node (Experimental.GraphicsDevice)
[INFO]: Creating CDevice - OpenGL 1.4
[INFO]: OpenGL 2.1 Mesa 11.1.0
[INFO]: Gallium 0.4 on VC4
[INFO]: Shadow mapping available (core)
[INFO]: Anisotropic filtering not available
[INFO]: Multisampling supported, max samples: 4
[INFO]: Auto-detecting VBO support
[INFO]: Core VBO supported
[INFO]: Maximum texture units: 8
[INFO]: Maximum texture size: 2048
[INFO]: Framebuffer supported (ARB)
[INFO]: Maximum renderbuffer size: 2048
[INFO]: CDevice created successfully
[INFO]: Closing joystick
[INFO]: Created shadow map texture: 1024x1024, depth 32
[ERROR]: Framebuffer incomplete: [ERROR]: 
[ERROR]: Could not create MSAA framebuffer, disabling MSAA

Unhandled exception occured!
==============================
SIGSEGV, segmentation fault
==============================

This is usually caused by a bug. Please report this on http://github.com/colobot/colobot/issues
including information on what you were doing before this happened and all the information below.
==============================
You seem to be running a custom compilation of version 0.1.7b-alpha, but please verify that.

The game was in phase PHASE_WELCOME1 (ID=0)
Last started level was: category=exercises chap=0 rank=0
==============================

____________________________________________________________

Compiled on Raspberry Pi 3 (e77f9dbd36469d5df5637f63b52da78d039c8ff1).

Btw. I think Colobot on Raspberry Pi (with OpenGL driver) has a huge potential taking into account Raspberry Pi educational purposes. Precompiled version (1.3) from the Raspbian repository seems to work. It runs smoothly but occasionally crushes/hangs with "Unable to handle kernel paging request at virtual address 0x....."  but I think it's not related with Colobot itself - it needs more testing.

**Comment by krzys-h** [comment]
It would be best if you could run it through gdb:
```
$ gdb ./colobot
(gdb) run
[after it crashes]
(gdb) backtrace
```
and post the output here.

I think this may be somehow related to MSAA considering the message above. Could you try to manually edit the config file (~/.local/share/colobot/colobot.ini) and change MSAA to 1 in [Graphics] section?

**Comment by azureblue** [comment]
The error is related to MSAA - after setting to 1 it starts.

gdb after running with MSAA set to 2:
`Starting program: /home/pi/Downloads/colobot/colobot/colobot -datadir ./data
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[INFO]: Colobot: Gold Edition 0.1.7b-alpha starting
[INFO]: Using data dir: './data'
[INFO]: Creating CApplication
[WARN]: Language path '/usr/local/share/locale' is invalid, assuming translation files not installed
[WARN]: Unable to load mods from directory './data/mods': boost::filesystem::directory_iterator::construct: No such file or directory: "./data/mods"
[INFO]: Data path: ./data
[INFO]: Save path: /home/pi/.local/share/colobot
[INFO]: Opening audio device...
[New Thread 0x742333d0 (LWP 1488)]
[Thread 0x742333d0 (LWP 1488) exited]
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
[New Thread 0x738ff3d0 (LWP 1489)]
[INFO]: Done.
[INFO]: CApplication created successfully
[New Thread 0x742333d0 (LWP 1490)]
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLVersion)
[INFO]: Error on parsing config file: No such node (Experimental.OpenGLProfile)
[INFO]: Error on parsing config file: No such node (Experimental.MSAA)
[INFO]: Error on parsing config file: No such node (Experimental.VSync)
[INFO]: No joysticks detected
[INFO]: Error on parsing config file: No such node (Experimental.GraphicsDevice)
[INFO]: Creating CDevice - OpenGL 1.4
[INFO]: OpenGL 2.1 Mesa 11.1.0
[INFO]: Gallium 0.4 on VC4
[INFO]: Shadow mapping available (core)
[INFO]: Anisotropic filtering not available
[INFO]: Multisampling supported, max samples: 4
[INFO]: Auto-detecting VBO support
[INFO]: Core VBO supported
[INFO]: Maximum texture units: 8
[INFO]: Maximum texture size: 2048
[INFO]: Framebuffer supported (ARB)
[INFO]: Maximum renderbuffer size: 2048
[INFO]: CDevice created successfully
[INFO]: Closing joystick
[INFO]: Created shadow map texture: 1024x1024, depth 32
[ERROR]: Framebuffer incomplete: [ERROR]: 
[ERROR]: Could not create MSAA framebuffer, disabling MSAA

Program received signal SIGSEGV, Segmentation fault.
0x000c0570 in Gfx::CEngine::UseMSAA(bool) ()
(gdb) backtrace
#0  0x000c0570 in Gfx::CEngine::UseMSAA(bool) ()
#1  0x000d0300 in Gfx::CEngine::Render() ()
#2  0x0008d380 in CApplication::Render() ()
#3  0x0008f85c in CApplication::Run() ()
#4  0x0008925c in main ()
`

I do believe that it's related with the Raspberry Pi [experimental - as they say] OpenGL driver since there are also errors in dmesg:
`
[   99.703413] [drm] num bos allocated: 581
[   99.703416] [drm] size bos allocated: 217736kb
[   99.703420] [drm] num bos used: 579
[   99.703423] [drm] size bos used: 208104kb
[   99.703427] [drm] num bos cached: 2
[   99.703430] [drm] size bos cached: 9632kb
[   99.703654] vc4-drm soc:gpu: failed to allocate buffer with size 4931584
[  101.462105] vc4-drm soc:gpu: failed to allocate buffer with size 8110080
[  101.462866] vc4-drm soc:gpu: failed to allocate buffer with size 8110080
[  101.462925] vc4-drm soc:gpu: failed to allocate buffer with size 8110080
[  101.462979] vc4-drm soc:gpu: failed to allocate buffer with size 8110080
[  101.463003] [drm:vc4_bo_create [vc4]] *ERROR* Failed to allocate from CMA:
[  101.463009] [drm] num bos allocated: 576
[  101.463013] [drm] size bos allocated: 202384kb
[  101.463016] [drm] num bos used: 574
[  101.463020] [drm] size bos used: 186544kb
[  101.463023] [drm] num bos cached: 2
[  101.463027] [drm] size bos cached: 15840kb
[  101.463276] vc4-drm soc:gpu: failed to allocate buffer with size 8110080
`

I guess you can't do much about.. 

Or do you maybe have an idea?

**Comment by azureblue** [comment]
Regarding the second problem - Unable to handle kernel paging request at virtual address.

It happens after the loading of "bigger" levels (by "bigger" I mean that it takes more time to load them" - I think), like 'gold digger'. It runs ok on levels like 'Spider 3'.

And the dmesg is:
```
[  149.575437] Unable to handle kernel paging request at virtual address 1bccf416
[  149.582739] pgd = a2d10000
[  149.585474] [1bccf416] *pgd=00000000
[  149.589062] Internal error: Oops: 5 [#1] SMP ARM
[  149.593671] Modules linked in: bnep bluetooth sg brcmfmac brcmutil cfg80211 evdev vc4 rfkill drm_kms_helper drm syscopyarea sysfillrect snd_bcm2835 sysimgblt fb_sys_fops snd_pcm snd_timer snd bcm2835_gpiomem i2c_bcm2708 bcm2835_wdt uio_pdrv_genirq uio i2c_dev fuse ipv6
[  149.617569] CPU: 0 PID: 1217 Comm: colobot Not tainted 4.4.13-v7+ #894
[  149.624087] Hardware name: BCM2709
[  149.627480] task: a2d31140 ti: b4a7e000 task.ti: b4a7e000
[  149.632876] PC is at kfree+0x54/0x1e8
[  149.636543] LR is at vc4_submit_cl_ioctl+0xf4/0x704 [vc4]
[  149.641935] pc : [<80149390>]    lr : [<7f1bc700>]    psr: 20000013
sp : b4a7fdc8  ip : 001f9aca  fp : b4a7fdf4
[  149.653404] r10: abd1b000  r9 : b82fb258  r8 : a2f10240
[  149.658620] r7 : 00001254  r6 : b82fa000  r5 : 7f1bc700  r4 : abd1b000
[  149.665138] r3 : 1bccf416  r2 : 00000007  r1 : 1bccf417  r0 : b82fa000
[  149.671658] Flags: nzCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
[  149.678785] Control: 10c5383d  Table: 22d1006a  DAC: 00000055
[  149.684522] Process colobot (pid: 1217, stack limit = 0xb4a7e210)
[  149.690607] Stack: (0xb4a7fdc8 to 0xb4a80000)
[  149.694958] fdc0:                   7f14ea68 b61b0400 abd1b000 00000496 a2525240 00001254
...
[  149.833869] ffe0: 7601507c 7edc76ac 75ffc2bc 765e902c 60000010 00000009 00000000 00000000
[  149.842059] [<80149390>] (kfree) from [<7f1bc700>] (vc4_submit_cl_ioctl+0xf4/0x704 [vc4])
[  149.850286] [<7f1bc700>] (vc4_submit_cl_ioctl [vc4]) from [<7f11b75c>] (drm_ioctl+0x144/0x49c [drm])
[  149.859445] [<7f11b75c>] (drm_ioctl [drm]) from [<801693b8>] (do_vfs_ioctl+0x424/0x614)
[  149.867445] [<801693b8>] (do_vfs_ioctl) from [<801695ec>] (SyS_ioctl+0x44/0x6c)
[  149.874754] [<801695ec>] (SyS_ioctl) from [<8000fb40>] (ret_fast_syscall+0x0/0x1c)
[  149.882319] Code: e083310c e5931014 e3110001 12413001 (e5932000) 
[  149.888545] ---[ end trace 084ffb15bb0596db ]---
```

**Comment by tomaszkax86** [comment]
It's unfortunate that it doesn't work properly. Do you happen to know which versions of OpenGL ES does it support? We might add OpenGL ES engines in some version. They might be more stable and could help port Colobot to Android and other mobile platforms.
