### ISSUE TITLE
SecondTexture works irrational

### ISSUE THREAD

**Issue by ghost** [colobot/colobot#847]
When you run a level with:
`SecondTexture rank=0`
and then with for example:
`SecondTexture rank=1`
Dirt textures aren't applied to the models and level looks like first level you started.

After restart the game run a level with for example:
`SecondTexture rank=1`
and then with:
`SecondTexture rank=0`
Dirt textures are pernamently applied to the models that.

That doesn't happen to the models that are newly loaded while playing in level.

It looks like models requires reload before start of every level.

**Comment by hexagonrecursion** [comment]
confirmed
game version 890333ef972bff5c182c3c93e9087d77368f1f62

**Comment by hexagonrecursion** [comment]
It looks like SecondTexture is applied to models only in AddBaseObjTriangles():

https://github.com/colobot/colobot/blob/890333ef972bff5c182c3c93e9087d77368f1f62/colobot-base/src/graphics/engine/engine.cpp#L4747-L4748

AddBaseObjTriangles() is called when adding a model, but then the same model is used in every level

https://github.com/colobot/colobot/blob/890333ef972bff5c182c3c93e9087d77368f1f62/colobot-base/src/graphics/engine/oldmodelmanager.cpp#L114

**Comment by hexagonrecursion** [comment]
Here are examples of callstacks:

```c++
#0  Gfx::CEngine::AddBaseObjTriangles (this=0x51e000000080, baseObjRank=400, triangles=std::vector of length 198, capacity 256 = {...})
    at /home/cdda/git/colobot/colobot-base/src/graphics/engine/engine.cpp:4760
#1  0x0000555555952f3d in Gfx::COldModelManager::LoadModel (this=0x507000038560, name=filesystem::path "human1c", mirrored=false, team=0)
    at /home/cdda/git/colobot/colobot-base/src/graphics/engine/oldmodelmanager.cpp:116
#2  0x0000555555953908 in Gfx::COldModelManager::AddModelReference (this=0x507000038560, fileName="human1c", mirrored=false, 
    objRank=400, team=0) at /home/cdda/git/colobot/colobot-base/src/graphics/engine/oldmodelmanager.cpp:126
#3  0x0000555555bb0a5d in CMotionHuman::Create (this=0x51d000140080, pos=..., angle=4.71238899, type=OBJECT_HUMAN, power=1, 
    modelManager=0x507000038560) at /home/cdda/git/colobot/colobot-base/src/object/motion/motionhuman.cpp:150
#4  0x00005555560712e3 in CBaseRobot::Create (params=..., modelManager=0x507000038560, engine=0x51e000000080)
    at /home/cdda/git/colobot/colobot-base/src/object/subclass/base_robot.cpp:91
#5  0x000055555600b5cc in CObjectFactory::CreateObject (this=0x50400004ca90, params=...)
    at /home/cdda/git/colobot/colobot-base/src/object/object_factory.cpp:315
#6  0x0000555555bd2235 in CObjectManager::CreateObject (this=0x50700003bc10, params=...)
    at /home/cdda/git/colobot/colobot-base/src/object/object_manager.cpp:148
#7  0x0000555555ae3f78 in CRobotMain::CreateScene (this=0x523000034900, soluce=false, fixScene=false, resetObject=false)
    at /home/cdda/git/colobot/colobot-base/src/level/robotmain.cpp:3445
#8  0x0000555555ab7ffa in CRobotMain::ChangePhase (this=0x523000034900, phase=PHASE_SIMUL)
    at /home/cdda/git/colobot/colobot-base/src/level/robotmain.cpp:554
#9  0x0000555555e64ac3 in Ui::CScreenLevelList::EventProcess (this=0x511000146e40, event=...)
    at /home/cdda/git/colobot/colobot-base/src/ui/screen/screen_level_list.cpp:355
#10 0x0000555555d0d8ed in Ui::CMainUserInterface::EventProcess (this=0x514000085c40, event=...)
    at /home/cdda/git/colobot/colobot-base/src/ui/mainui.cpp:250
#11 0x0000555555aba0ba in CRobotMain::ProcessEvent (this=0x523000034900, event=...)
    at /home/cdda/git/colobot/colobot-base/src/level/robotmain.cpp:658
#12 0x00005555557cd3de in CController::ProcessEvent (this=0x5020000d9ab0, event=...)
    at /home/cdda/git/colobot/colobot-base/src/app/controller.cpp:53
#13 0x000055555577d688 in CApplication::Run (this=0x7ffff3b01530) at /home/cdda/git/colobot/colobot-base/src/app/app.cpp:1139
#14 0x0000555555764d0d in main (argc=3, argv=0x7fffffffe8e8) at /home/cdda/git/colobot/colobot-app/src/main.cpp:172
```

```c++
#0  Gfx::CEngine::AddBaseObjTriangles (this=0x51e000000080, baseObjRank=424, triangles=std::vector of length 32, capacity 32 = {...})
    at /home/cdda/git/colobot/colobot-base/src/graphics/engine/engine.cpp:4760
#1  0x0000555555952f3d in Gfx::COldModelManager::LoadModel (this=0x507000038560, name=filesystem::path "power", mirrored=false, team=0)
    at /home/cdda/git/colobot/colobot-base/src/graphics/engine/oldmodelmanager.cpp:116
#2  0x0000555555953f10 in Gfx::COldModelManager::AddModelCopy (this=0x507000038560, fileName="power", mirrored=false, objRank=427, team=0)
    at /home/cdda/git/colobot/colobot-base/src/graphics/engine/oldmodelmanager.cpp:143
#3  0x000055555600c08a in CObjectFactory::CreateResource (this=0x50400004ca90, params=...) at /home/cdda/git/colobot/colobot-base/src/object/object_factory.cpp:375
#4  0x000055555600b19a in CObjectFactory::CreateObject (this=0x50400004ca90, params=...) at /home/cdda/git/colobot/colobot-base/src/object/object_factory.cpp:137
#5  0x0000555555bd2235 in CObjectManager::CreateObject (this=0x50700003bc10, params=...) at /home/cdda/git/colobot/colobot-base/src/object/object_manager.cpp:148
#6  0x0000555555bd27ff in CObjectManager::CreateObject (this=0x50700003bc10, pos=<error reading variable: Cannot access memory at address 0xfffffffeffffff70>, angle=0, type=OBJECT_POWER, power=1)
    at /home/cdda/git/colobot/colobot-base/src/object/object_manager.cpp:167
#7  0x0000555555ff59cf in CMotionVehicle::Create (this=0x51100033e900, pos=..., angle=4.71238899, type=OBJECT_MOBILEwa, power=1, modelManager=0x507000038560)
    at /home/cdda/git/colobot/colobot-base/src/object/motion/motionvehicle.cpp:1070
#8  0x00005555560712e3 in CBaseRobot::Create (params=..., modelManager=0x507000038560, engine=0x51e000000080) at /home/cdda/git/colobot/colobot-base/src/object/subclass/base_robot.cpp:91
#9  0x000055555600b5cc in CObjectFactory::CreateObject (this=0x50400004ca90, params=...) at /home/cdda/git/colobot/colobot-base/src/object/object_factory.cpp:315
#10 0x0000555555bd2235 in CObjectManager::CreateObject (this=0x50700003bc10, params=...) at /home/cdda/git/colobot/colobot-base/src/object/object_manager.cpp:148
#11 0x0000555555ae3f78 in CRobotMain::CreateScene (this=0x523000034900, soluce=false, fixScene=false, resetObject=false) at /home/cdda/git/colobot/colobot-base/src/level/robotmain.cpp:3445
#12 0x0000555555ab7ffa in CRobotMain::ChangePhase (this=0x523000034900, phase=PHASE_SIMUL) at /home/cdda/git/colobot/colobot-base/src/level/robotmain.cpp:554
#13 0x0000555555e64ac3 in Ui::CScreenLevelList::EventProcess (this=0x511000146e40, event=...) at /home/cdda/git/colobot/colobot-base/src/ui/screen/screen_level_list.cpp:355
#14 0x0000555555d0d8ed in Ui::CMainUserInterface::EventProcess (this=0x514000085c40, event=...) at /home/cdda/git/colobot/colobot-base/src/ui/mainui.cpp:250
#15 0x0000555555aba0ba in CRobotMain::ProcessEvent (this=0x523000034900, event=...) at /home/cdda/git/colobot/colobot-base/src/level/robotmain.cpp:658
#16 0x00005555557cd3de in CController::ProcessEvent (this=0x5020000d9ab0, event=...) at /home/cdda/git/colobot/colobot-base/src/app/controller.cpp:53
#17 0x000055555577d688 in CApplication::Run (this=0x7ffff3b01530) at /home/cdda/git/colobot/colobot-base/src/app/app.cpp:1139
#18 0x0000555555764d0d in main (argc=3, argv=0x7fffffffe8e8) at /home/cdda/git/colobot/colobot-app/src/main.cpp:172
```
