### ISSUE TITLE
Initializing variables in classes using functions outside the constructor crashes the game

### ISSUE THREAD

**Issue by dmicher** [colobot/colobot#981]
First of all I'm a newbie in colobot & programming, and I'm just start learning. So I know that I can do some idiot mistakes. Second is my English... I hope that it is not so bad as I think. =)

I've got a game crash, and colobot told me to public an issue here. "Why not?" - I think.

> Unhandled exception occured!
> SIGSEGV, segmentation fault
> This is usualy caused by a bug.... bla-bla-bla
> You are running official 0.1.10-alpfa build.
>
> The game was in phase PHASE_SIMUL (ID=7)
> Last started level wasL cathegory=mission chap=2 rank=4

My laptop is win10, Intel(R) Celeron(R) CPU N3050, 1.60 GHz, RAM 2.00 Gb.

I was compilling next code when game crashed:

```
public class airGrabber {
	object unit = radar (WingedGrabber);
	void func () {wait (1);}
}
extern void object::landGrabber()
{
	/*
	deliver (radar(Titanium).position, flatspace ( between (radar(SpaceShip).position, this.position), 6, 20, 100, 6));
	build (Converter);
	object CV = radar(Converter);
	deliver (radar(TitaniumOre).position, CV.position);
	move (-4);
	wait (14);
	*/
}
void noErrorGoto(point pos) {
	errmode(0);
	while ( goto(pos) != 0 )
	{
		wait(5);
		message ("Waiting for free place");
	}
}
void deliver (point from, point to, int plan = 0) {
	/* Plan 0: from, grab, to, drop;
	 * Plan 1: from, grab, to
	 * Plan 2:             to, drop;
	*/
	
	if (plan == 0 or plan == 1) {
		noErrorGoto (from);
		grab();
	}
	noErrorGoto (to);
	if (plan == 0 or plan ==2) drop();
}
point between (point A, point B) {
	point C;
	    C.x = 0.5*A.x + 0.5*B.x;
	    C.y = 0.5*A.y + 0.5*B.y;
	    C.z = 0.5*A.z + 0.5*B.z;
	return C;
}
```

What did I miss in my code?.. or IQ? =))

And yes, I know that my code isn't complete at all. It's a just pre-draft.

**Comment by tomangelo2** [comment]
Confirmed
```gdb
Thread 1 received signal SIGSEGV, Segmentation fault.
0x004ccbd3 in std::_Function_handler<bool (std::vector<ObjectType, std::allocator<ObjectType> >, float, float, float, float, bool, RadarFilter), CScriptFunctions::rRadar(CBot::CBotVar*, CBot::CBotVar*, int&, void*)::{lambda(std::vector<ObjectType, std::allocator<ObjectType> >, float, float, float, float, bool, RadarFilter)#1}>::_M_invoke(std::_Any_data const&, std::vector<ObjectType, std::allocator<ObjectType> >&&, float&&, std::vector<ObjectType, std::allocator<ObjectType> >&&, std::vector<ObjectType, std::allocator<ObjectType> >&&, std::vector<ObjectType, std::allocator<ObjectType> >&&, bool&&, RadarFilter&&) ()
(gdb) bt
#0  0x004ccbd3 in std::_Function_handler<bool (std::vector<ObjectType, std::allocator<ObjectType> >, float, float, float, float, bool, RadarFilter), CScriptFunctions::rRadar(CBot::CBotVar*, CBot::CBotVar*, int&, void*)::{lambda(std::vector<ObjectType, std::allocator<ObjectType> >, float, float, float, float, bool, RadarFilter)#1}>::_M_invoke(std::_Any_data const&, std::vector<ObjectType, std::allocator<ObjectType> >&&, float&&, std::vector<ObjectType, std::allocator<ObjectType> >&&, std::vector<ObjectType, std::allocator<ObjectType> >&&, std::vector<ObjectType, std::allocator<ObjectType> >&&, bool&&, RadarFilter&&) ()
#1  0x004d77f4 in runRadar(CBot::CBotVar*, std::function<bool (std::vector<ObjectType, std::allocator<ObjectType> >, float, float, float, float, bool, RadarFilter)>) ()
#2  0x004d7979 in CScriptFunctions::rRadar(CBot::CBotVar*, CBot::CBotVar*, int&, void*) ()
#3  0x005fc119 in CBot::CBotExternalCallDefault::Run(CBot::CBotVar*, CBot::CBotStack*) ()
#4  0x005fc9bd in CBot::CBotExternalCallList::DoCall(CBot::CBotToken*, CBot::CBotVar*, CBot::CBotVar**, CBot::CBotStack*, CBot::CBotTypResult const&) ()
#5  0x0060ee2d in CBot::CBotStack::ExecuteCall(long&, CBot::CBotToken*, CBot::CBotVar**, CBot::CBotTypResult const&) ()
#6  0x0062a9a7 in CBot::CBotInstrCall::Execute(CBot::CBotStack*&) ()
#7  0x00602a21 in CBot::CBotInstr::Execute(CBot::CBotStack*&, CBot::CBotVar*)
    ()
#8  0x00615472 in CBot::CBotVarClass::SetClass(CBot::CBotClass*) ()
#9  0x00616188 in CBot::CBotVarClass::CBotVarClass(CBot::CBotToken const&, CBot::CBotTypResult const&) ()
#10 0x00613fd0 in CBot::CBotVar::Create(CBot::CBotToken const&, CBot::CBotTypResult) ()
#11 0x005fa9cc in CBot::CBotClass::CompileDefItem(CBot::CBotToken*&, CBot::CBotCStack*, bool) ()
#12 0x005fb174 in CBot::CBotClass::Compile(CBot::CBotToken*&, CBot::CBotCStack*) ()
#13 0x0060df4a in CBot::CBotProgram::Compile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, void*) ()
#14 0x005cbab1 in CScript::Compile() ()
#15 0x005cebe2 in CScript::GetScript(Ui::CEdit*) ()
#16 0x0051f270 in Ui::CStudio::EventProcess(Event const&) ()
#17 0x00502a99 in Ui::CObjectInterface::EventProcess(Event const&) ()
#18 0x004a9737 in COldObject::EventProcess(Event const&) ()
#19 0x0048e2b9 in CRobotMain::EventObject(Event const&) ()
#20 0x00491b78 in CRobotMain::ProcessEvent(Event&) ()
#21 0x004057a5 in CApplication::Run() ()
#22 0x00401b99 in SDL_main ()
#23 0x00632dc4 in main_getcmdline ()
#24 0x00632ec5 in WinMain@16 ()
#25 0x006999ad in main (flags=1, cmdline=0x34c128, inst=0x341ba0)
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c:18
(gdb)
```

**Comment by dmicher** [comment]
Thank you for your help & good luck with this bug.

P.S. I believe the first part of comment (before "edit") is some sort of dark magic for Higher Initiation Masters only =))

**Comment by tomangelo2** [comment]
I'd rather keep it open, as we should replace crashes with in-game compilation error.
Yes, this part before edit is for developers to give some details about what's wrong.

**Comment by dmicher** [comment]
ok

**Comment by Casteele72** [comment]
> I'd rather keep it open, as we should replace crashes with in-game compilation error. Yes, this part before edit is for developers to give some details about what's wrong.

Most definitely. I copied some code from somewhere else (Reddit, I think?) to try to work around several other issues I have been having, and their code initialized the variables the way my code did. A compilation error would let me know that it is not correct, while the game SEGVing tells me nothing.

**Comment by hexagonrecursion** [comment]
I see two paths to fixing this:
1. Syntactically restrict the expressions allowed in static initializers (ban function calls, method calls and the new keyword)
2. Delay static member initialization until _after_ the whole program is compiled - like how C++, java, C# and many other languages do this.
